### PR TITLE
[WIP] Add Area to display participating projects

### PR DESCRIPTION
**Pull request by M-Zuber**
As per #45 

Page:
- [ ] Instructions for how to add your project
- [ ]  Encourage people to encourage projects to get involved

Per Project:
- [x] Repository
- [x] Contributing docs if exists
- [x] Languages written in
- [x] Link to label for easy starter issues
- [x] Where to go to contact maintainers

### CODE REVIEW

**Comment by M-Zuber** [comment]
My copy-fu and rebase-fu are not currently working.
But here is the basis for an area to display the projects that are particiapting

**Comment by M-Zuber** [comment]
ping

**Comment by davidmiller** [comment]
@M-Zuber Thanks for this - and sorry for the delay :( 
Last week or two have been hectic running this conference: http://ukhealthcamp.com/ - ate all of my free time.

Recovered now though and will take a look at this ASAP - I think it needs a couple of seed projects though - that was the thinking behind https://twitter.com/pullrequestday/status/663697268437073920 and https://twitter.com/pullrequestday/status/663697012630683648 although they never responded :(

**Comment by M-Zuber** [comment]
I understand the concept of being busy,  no worries :smile:

More then happy to add a few seeds. I'll try and get to it as soon as i can

**Comment by M-Zuber** [comment]
i've added one project. looking for more

**Comment by M-Zuber** [comment]
@davidmiller ping

**Comment by M-Zuber** [comment]
:smile: 
Thank you.
I will try and get some other projects in there if I can

**Pull request merged**
