### PR TITLE
Ignore .jekyll-metadata

### PR DESCRIPTION
**Pull request by andylolz**
Time to upgrade to jekyll 3.

### CODE REVIEW

**Comment by davidmiller** [comment]
I have no real idea what that is, but happy to take your lead :)

**Comment by andylolz** [comment]
It’s a new thing in Jekyll 3, and relates to only building modified stuff. Something we really needed for the YNMP-Read site!

**Comment by symroe** [comment]
@andylolz  Sadly I don't think it works with data generated sections ;/

**Comment by andylolz** [comment]
orly? Oh :(

**Pull request merged**
